# SUYASH PRATAP SINGH

## Import modules

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Read and display test,train data

In [3]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [4]:
df_train.head()

Id  Age  Attrition BusinessTravel              Department  \
0   1   30          0     Non-Travel  Research & Development   
1   2   36          0  Travel_Rarely  Research & Development   
2   3   55          1  Travel_Rarely                   Sales   
3   4   39          0  Travel_Rarely  Research & Development   
4   5   37          0  Travel_Rarely  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeNumber  \
0                 2          3        Medical             571   
1                12          4  Life Sciences            1614   
2                 2          1        Medical             842   
3                24          1  Life Sciences            2014   
4                 3          3          Other             689   

   EnvironmentSatisfaction  ... PerformanceRating  StockOptionLevel  \
0                        3  ...                 3                 0   
1                        3  ...                 3                 2   
2                        3  ...                 3                 0   
3                        1  ...                 3                 0   
4                        3  ...                 3                 1   

  TotalWorkingYears  TrainingTimesLastYear YearsAtCompany  YearsInCurrentRole  \
0                12                      2             11                   7   
1                 7                      2              3                   2   
2                12                      3              9                   7   
3                18                      2              7                   7   
4                10                      2             10                   7   

   YearsSinceLastPromotion YearsWithCurrManager  CommunicationSkill  Behaviour  
0                        6                    7                   4          1  
1                        1                    1                   2          1  
2                        7                    3                   5          1  
3                        1                    7                   4          1  
4                        7                    8                   1          1  

[5 rows x 29 columns]

In [5]:
df_test.head()

Id  Age BusinessTravel              Department  DistanceFromHome  \
0   1   28  Travel_Rarely  Research & Development                 9   
1   2   31  Travel_Rarely                   Sales                 6   
2   3   37  Travel_Rarely  Research & Development                 6   
3   4   42  Travel_Rarely  Research & Development                 1   
4   5   45     Non-Travel  Research & Development                 4   

   Education EducationField  EmployeeNumber  EnvironmentSatisfaction  Gender  \
0          3        Medical             377                        4    Male   
1          4        Medical             653                        1    Male   
2          3        Medical             474                        3    Male   
3          2  Life Sciences             827                        4  Female   
4          2  Life Sciences             972                        3    Male   

   ...  PerformanceRating StockOptionLevel  TotalWorkingYears  \
0  ...                  4                1                  5   
1  ...                  4                2                 13   
2  ...                  3                2                 13   
3  ...                  3                1                  8   
4  ...                  3                0                  9   

  TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  \
0                     3               5                   2   
1                     4               7                   7   
2                     2               7                   7   
3                     4               4                   3   
4                     5               9                   7   

  YearsSinceLastPromotion  YearsWithCurrManager  CommunicationSkill  Behaviour  
0                       0                     4                   5          1  
1                       5                     7                   3          1  
2                       6                     7                   4          1  
3                       0                     2                   5          1  
4                       0                     8                   2          1  

[5 rows x 28 columns]

In [6]:
import sklearn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
df_train['BusinessTravel'] = le.fit_transform(df_train['BusinessTravel'])
df_train['Department'] = le.fit_transform(df_train['Department'])
df_train['EducationField'] = le.fit_transform(df_train['EducationField'])
df_train['Gender'] = le.fit_transform(df_train['Gender'])
df_train['JobRole'] = le.fit_transform(df_train['JobRole'])
df_train['OverTime'] = le.fit_transform(df_train['OverTime'])
df_train['MaritalStatus'] = le.fit_transform(df_train['MaritalStatus'])

In [8]:
df_test['BusinessTravel'] = le.fit_transform(df_test['BusinessTravel'])
df_test['Department'] = le.fit_transform(df_test['Department'])
df_test['EducationField'] = le.fit_transform(df_test['EducationField'])
df_test['Gender'] = le.fit_transform(df_test['Gender'])
df_test['JobRole'] = le.fit_transform(df_test['JobRole'])
df_test['OverTime'] = le.fit_transform(df_test['OverTime'])
df_test['MaritalStatus'] = le.fit_transform(df_test['MaritalStatus'])


## Split and train model

In [9]:
x_train = df_train.drop('Attrition',axis=1)
y_train = df_train['Attrition']

In [10]:
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [11]:
logmod = LogisticRegression()
logmod.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predictions

In [12]:
predictions = logmod.predict_proba(df_test)[:,1]


In [13]:
predictions

array([0.01208108, 0.010207  , 0.03411493, 0.01342378, 0.00345171,
       0.00585857, 0.02451556, 0.00483406, 0.04373394, 0.00667176,
       0.00307958, 0.01214782, 0.00432103, 0.01026016, 0.00643295,
       0.02047622, 0.03594555, 0.02543464, 0.00715538, 0.00600591,
       0.00338454, 0.06309095, 0.00525556, 0.01706627, 0.01965157,
       0.01692076, 0.00523127, 0.00456882, 0.02959916, 0.04152786,
       0.02083445, 0.01925312, 0.03527997, 0.02932389, 0.00172269,
       0.01852118, 0.0048305 , 0.00145482, 0.03149707, 0.0211906 ,
       0.11260854, 0.01523191, 0.00602617, 0.01847705, 0.00240073,
       0.01147902, 0.02807493, 0.00821783, 0.00108484, 0.05086757,
       0.01743621, 0.01305055, 0.04824505, 0.05882326, 0.12673709,
       0.02031884, 0.01150205, 0.09199504, 0.00356721, 0.02237163,
       0.00802851, 0.01829087, 0.01329241, 0.01966203, 0.03026839,
       0.01552543, 0.04613466, 0.0250875 , 0.02386032, 0.04274029,
       0.08192271, 0.00691   , 0.01672977, 0.11222455, 0.02157

In [14]:
df1 = pd.DataFrame(df_test['Id'],columns=['Id'])

In [15]:
df1.head()

Id
0   1
1   2
2   3
3   4
4   5

In [16]:
df2 =pd.DataFrame(predictions,columns=['Attrition'])

In [17]:
df2.head()

Attrition
0   0.012081
1   0.010207
2   0.034115
3   0.013424
4   0.003452

In [18]:
df_final = pd.concat([df1,df2],axis=1)

In [19]:
df_final

Id  Attrition
0      1   0.012081
1      2   0.010207
2      3   0.034115
3      4   0.013424
4      5   0.003452
..   ...        ...
465  466   0.151937
466  467   0.368939
467  468   0.287627
468  469   0.342007
469  470   0.046313

[470 rows x 2 columns]

In [20]:
df_final = df_final.set_index('Id')

In [21]:
df_final.head()

Attrition
Id           
1    0.012081
2    0.010207
3    0.034115
4    0.013424
5    0.003452

In [22]:
df_final.to_csv('Submission1_U011P5R9NRK.csv')

## Using Randomforest Classifier

In [23]:
from sklearn.model_selection import train_test_split
x_train, cvx_test, y_train, cvy_test = train_test_split(x_train, y_train, test_size=0.2, random_state=420)

In [24]:

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=10,n_estimators=200, criterion='entropy', random_state=420)
model.fit(x_train, y_train)
predict_train = model.predict_proba(x_train)[:,1]
predict_test  = model.predict_proba(cvx_test)[:,1]

model.score(cvx_test, cvy_test)

0.911042944785276

In [25]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(cvy_test, model.predict(cvx_test))

array([[157,   3],
       [ 26, 140]], dtype=int64)

In [26]:
confusion_matrix(y_train, model.predict(x_train))


array([[683,   0],
       [  0, 619]], dtype=int64)

In [27]:
prediction = model.predict_proba(df_test)[:,1]


In [28]:
output = pd.Series(prediction)
output_final = pd.concat([df_test['Id'], output], axis=1)
output_final.columns=['Id', 'Attrition']
output_final.set_index('Id',inplace=True)
output_final.describe()


Attrition
count  470.000000
mean     0.168210
std      0.132790
min      0.006138
25%      0.073234
50%      0.127562
75%      0.210048
max      0.741574

In [29]:
output_final

Attrition
Id            
1     0.120083
2     0.100939
3     0.113436
4     0.174687
5     0.071733
..         ...
466   0.368309
467   0.689066
468   0.340234
469   0.074351
470   0.076819

[470 rows x 1 columns]

In [30]:
output_final.to_csv('Submission2_U011P5R9NRK.csv')

## Simple neural network

In [85]:
import keras
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import binary_crossentropy

### Hyperparameters

In [91]:
activation_function = 'relu'
loss = 'binary_crossentropy'
hidden_units_layer_1 = 28
hidden_units_layer_2 = 32
output_units = 1
batch_size = 10
epochs = 25
learning_rate = 0.001

In [92]:
model = Sequential([
    Dense(hidden_units_layer_1, input_dim=28, activation=activation_function),
    Dense(hidden_units_layer_2, activation=activation_function),
    Dense(output_units, activation='sigmoid')
])
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_32 (Dense)             (None, 28)                812       
_________________________________________________________________
dense_33 (Dense)             (None, 32)                928       
_________________________________________________________________
dense_34 (Dense)             (None, 1)                 33        
Total params: 1,773
Trainable params: 1,773
Non-trainable params: 0
_________________________________________________________________


In [93]:
optimizer = Adam(lr = 0.0001)

In [94]:
model.compile(optimizer, loss= loss, metrics=['accuracy'])


In [95]:
history = model.fit(x_train, y_train, validation_split=0.2, batch_size=batch_size, epochs=epochs, shuffle=True, verbose=2)


Train on 1041 samples, validate on 261 samples
Epoch 1/25
 - 0s - loss: 576.5354 - accuracy: 0.4697 - val_loss: 261.6982 - val_accuracy: 0.4981
Epoch 2/25
 - 0s - loss: 88.4715 - accuracy: 0.5130 - val_loss: 30.8311 - val_accuracy: 0.5441
Epoch 3/25
 - 0s - loss: 14.6890 - accuracy: 0.6196 - val_loss: 8.8544 - val_accuracy: 0.6245
Epoch 4/25
 - 0s - loss: 5.5520 - accuracy: 0.6830 - val_loss: 5.6700 - val_accuracy: 0.6705
Epoch 5/25
 - 0s - loss: 4.0768 - accuracy: 0.7166 - val_loss: 4.7602 - val_accuracy: 0.6973
Epoch 6/25
 - 0s - loss: 3.5984 - accuracy: 0.7406 - val_loss: 3.8413 - val_accuracy: 0.7050
Epoch 7/25
 - 0s - loss: 3.4512 - accuracy: 0.7397 - val_loss: 3.7946 - val_accuracy: 0.7241
Epoch 8/25
 - 0s - loss: 3.1718 - accuracy: 0.7426 - val_loss: 3.2116 - val_accuracy: 0.7126
Epoch 9/25
 - 0s - loss: 2.9110 - accuracy: 0.7493 - val_loss: 3.7358 - val_accuracy: 0.6897
Epoch 10/25
 - 0s - loss: 2.9591 - accuracy: 0.7445 - val_loss: 2.9348 - val_accuracy: 0.7318
Epoch 11/25
 - 

In [97]:
predictions1 = model.predict_classes(df_test,batch_size=100,verbose=0)


# THANK YOU